const { connectDB } = require('./db')

const connection = connectDB();

/**
 * Get List of Results
 * @returns {Array}
 */
function getList() {
    const data = [{
        "id": 1,
        "first_name": "Berri",
        "last_name": "Moorerud",
        "email": "bmoorerud0@toplist.cz",
        "gender": "Genderfluid",
        "ip_address": "88.151.57.29"
    }, {
        "id": 2,
        "first_name": "Woodrow",
        "last_name": "Alessandrini",
        "email": "walessandrini1@opensource.org",
        "gender": "Agender",
        "ip_address": "226.76.224.209"
    }, {
        "id": 3,
        "first_name": "Candida",
        "last_name": "Paddle",
        "email": "cpaddle2@foxnews.com",
        "gender": "Bigender",
        "ip_address": "189.26.179.100"
    }, {
        "id": 4,
        "first_name": "Myranda",
        "last_name": "Roust",
        "email": "mroust3@techcrunch.com",
        "gender": "Female",
        "ip_address": "172.25.94.186"
    }, {
        "id": 5,
        "first_name": "Denny",
        "last_name": "Yurkin",
        "email": "dyurkin4@ask.com",
        "gender": "Female",
        "ip_address": "94.96.177.69"
    }, {
        "id": 6,
        "first_name": "Keri",
        "last_name": "Lorenzo",
        "email": "klorenzo5@slideshare.net",
        "gender": "Bigender",
        "ip_address": "101.233.111.87"
    }, {
        "id": 7,
        "first_name": "Zorina",
        "last_name": "Titcumb",
        "email": "ztitcumb6@cdbaby.com",
        "gender": "Genderqueer",
        "ip_address": "106.76.199.102"
    }, {
        "id": 8,
        "first_name": "Ella",
        "last_name": "Bampfield",
        "email": "ebampfield7@uiuc.edu",
        "gender": "Female",
        "ip_address": "216.94.202.202"
    }, {
        "id": 9,
        "first_name": "Maurizia",
        "last_name": "O'Carrol",
        "email": "mocarrol8@ca.gov",
        "gender": "Polygender",
        "ip_address": "7.118.163.162"
    }, {
        "id": 10,
        "first_name": "Ynez",
        "last_name": "Dibbs",
        "email": "ydibbs9@webmd.com",
        "gender": "Genderfluid",
        "ip_address": "165.116.45.80"
    }, {
        "id": 11,
        "first_name": "Corby",
        "last_name": "Hartop",
        "email": "chartopa@virginia.edu",
        "gender": "Polygender",
        "ip_address": "53.34.124.67"
    }, {
        "id": 12,
        "first_name": "Pavla",
        "last_name": "Klagge",
        "email": "pklaggeb@hp.com",
        "gender": "Male",
        "ip_address": "120.209.56.97"
    }, {
        "id": 13,
        "first_name": "Blinnie",
        "last_name": "Windybank",
        "email": "bwindybankc@fc2.com",
        "gender": "Agender",
        "ip_address": "238.233.207.126"
    }, {
        "id": 14,
        "first_name": "Sam",
        "last_name": "Savidge",
        "email": "ssavidged@admin.ch",
        "gender": "Non-binary",
        "ip_address": "111.15.78.202"
    }, {
        "id": 15,
        "first_name": "Modesta",
        "last_name": "Grimoldby",
        "email": "mgrimoldbye@economist.com",
        "gender": "Female",
        "ip_address": "149.88.127.131"
    }, {
        "id": 16,
        "first_name": "Marjy",
        "last_name": "Fry",
        "email": "mfryf@bandcamp.com",
        "gender": "Non-binary",
        "ip_address": "165.246.117.148"
    }, {
        "id": 17,
        "first_name": "Cyrillus",
        "last_name": "Reimers",
        "email": "creimersg@illinois.edu",
        "gender": "Male",
        "ip_address": "9.124.224.108"
    }, {
        "id": 18,
        "first_name": "Annelise",
        "last_name": "Weatherhill",
        "email": "aweatherhillh@hibu.com",
        "gender": "Female",
        "ip_address": "178.78.117.92"
    }, {
        "id": 19,
        "first_name": "Goldia",
        "last_name": "Pakenham",
        "email": "gpakenhami@ftc.gov",
        "gender": "Genderfluid",
        "ip_address": "8.91.39.29"
    }, {
        "id": 20,
        "first_name": "Sterling",
        "last_name": "Hydes",
        "email": "shydesj@bloomberg.com",
        "gender": "Genderqueer",
        "ip_address": "62.139.44.24"
    }, {
        "id": 21,
        "first_name": "Kora",
        "last_name": "Robatham",
        "email": "krobathamk@prnewswire.com",
        "gender": "Non-binary",
        "ip_address": "38.91.53.83"
    }, {
        "id": 22,
        "first_name": "Corey",
        "last_name": "Tompkin",
        "email": "ctompkinl@slate.com",
        "gender": "Female",
        "ip_address": "78.62.81.170"
    }, {
        "id": 23,
        "first_name": "Anallese",
        "last_name": "Busst",
        "email": "abusstm@scribd.com",
        "gender": "Male",
        "ip_address": "85.106.10.63"
    }, {
        "id": 24,
        "first_name": "Mallorie",
        "last_name": "Goudy",
        "email": "mgoudyn@dell.com",
        "gender": "Genderfluid",
        "ip_address": "187.43.251.114"
    }, {
        "id": 25,
        "first_name": "Thorstein",
        "last_name": "Brunsdon",
        "email": "tbrunsdono@behance.net",
        "gender": "Non-binary",
        "ip_address": "197.64.111.161"
    }, {
        "id": 26,
        "first_name": "Laurene",
        "last_name": "Orthmann",
        "email": "lorthmannp@tumblr.com",
        "gender": "Genderqueer",
        "ip_address": "204.120.232.137"
    }, {
        "id": 27,
        "first_name": "Andree",
        "last_name": "Latham",
        "email": "alathamq@cam.ac.uk",
        "gender": "Female",
        "ip_address": "196.16.160.63"
    }, {
        "id": 28,
        "first_name": "Minda",
        "last_name": "Ducarne",
        "email": "mducarner@people.com.cn",
        "gender": "Genderfluid",
        "ip_address": "28.147.111.83"
    }, {
        "id": 29,
        "first_name": "Laura",
        "last_name": "Eubank",
        "email": "leubanks@de.vu",
        "gender": "Bigender",
        "ip_address": "221.26.40.63"
    }, {
        "id": 30,
        "first_name": "Celestyn",
        "last_name": "Coppins",
        "email": "ccoppinst@addthis.com",
        "gender": "Genderqueer",
        "ip_address": "148.145.198.142"
    }, {
        "id": 31,
        "first_name": "Carey",
        "last_name": "Castro",
        "email": "ccastrou@miibeian.gov.cn",
        "gender": "Female",
        "ip_address": "5.185.93.95"
    }, {
        "id": 32,
        "first_name": "Quinn",
        "last_name": "Vardy",
        "email": "qvardyv@blogs.com",
        "gender": "Non-binary",
        "ip_address": "176.220.147.169"
    }, {
        "id": 33,
        "first_name": "Nessy",
        "last_name": "Vida",
        "email": "nvidaw@army.mil",
        "gender": "Male",
        "ip_address": "21.120.82.164"
    }, {
        "id": 34,
        "first_name": "Joanne",
        "last_name": "Choppen",
        "email": "jchoppenx@nhs.uk",
        "gender": "Genderfluid",
        "ip_address": "125.26.110.42"
    }, {
        "id": 35,
        "first_name": "Jeana",
        "last_name": "Cottle",
        "email": "jcottley@ovh.net",
        "gender": "Male",
        "ip_address": "125.67.9.10"
    }, {
        "id": 36,
        "first_name": "Erik",
        "last_name": "Daggett",
        "email": "edaggettz@yahoo.com",
        "gender": "Male",
        "ip_address": "42.170.216.253"
    }, {
        "id": 37,
        "first_name": "Anthony",
        "last_name": "Callington",
        "email": "acallington10@telegraph.co.uk",
        "gender": "Female",
        "ip_address": "238.253.183.40"
    }, {
        "id": 38,
        "first_name": "Kyla",
        "last_name": "Reignard",
        "email": "kreignard11@si.edu",
        "gender": "Genderfluid",
        "ip_address": "45.33.141.22"
    }, {
        "id": 39,
        "first_name": "Staford",
        "last_name": "Raft",
        "email": "sraft12@t.co",
        "gender": "Genderqueer",
        "ip_address": "73.122.228.221"
    }, {
        "id": 40,
        "first_name": "Camel",
        "last_name": "Castle",
        "email": "ccastle13@reverbnation.com",
        "gender": "Female",
        "ip_address": "189.222.134.187"
    }, {
        "id": 41,
        "first_name": "Guillaume",
        "last_name": "Noto",
        "email": "gnoto14@fda.gov",
        "gender": "Genderfluid",
        "ip_address": "10.53.27.149"
    }, {
        "id": 42,
        "first_name": "Lavena",
        "last_name": "Szreter",
        "email": "lszreter15@nasa.gov",
        "gender": "Male",
        "ip_address": "226.24.172.221"
    }, {
        "id": 43,
        "first_name": "Lucilia",
        "last_name": "Biever",
        "email": "lbiever16@npr.org",
        "gender": "Polygender",
        "ip_address": "185.125.56.184"
    }, {
        "id": 44,
        "first_name": "Donielle",
        "last_name": "Whitland",
        "email": "dwhitland17@princeton.edu",
        "gender": "Agender",
        "ip_address": "198.225.147.217"
    }, {
        "id": 45,
        "first_name": "Lilly",
        "last_name": "Tremmil",
        "email": "ltremmil18@eventbrite.com",
        "gender": "Agender",
        "ip_address": "64.247.119.221"
    }, {
        "id": 46,
        "first_name": "Randy",
        "last_name": "De Biasi",
        "email": "rdebiasi19@usatoday.com",
        "gender": "Polygender",
        "ip_address": "72.15.86.215"
    }, {
        "id": 47,
        "first_name": "Glennie",
        "last_name": "Shelley",
        "email": "gshelley1a@craigslist.org",
        "gender": "Female",
        "ip_address": "24.132.253.167"
    }, {
        "id": 48,
        "first_name": "Rafaelita",
        "last_name": "Thieme",
        "email": "rthieme1b@weibo.com",
        "gender": "Bigender",
        "ip_address": "113.17.213.86"
    }, {
        "id": 49,
        "first_name": "Livvie",
        "last_name": "Lampkin",
        "email": "llampkin1c@mysql.com",
        "gender": "Male",
        "ip_address": "91.86.194.186"
    }, {
        "id": 50,
        "first_name": "Rafaela",
        "last_name": "Fetter",
        "email": "rfetter1d@bizjournals.com",
        "gender": "Polygender",
        "ip_address": "239.178.133.9"
    }, {
        "id": 51,
        "first_name": "Ewan",
        "last_name": "Ayce",
        "email": "eayce1e@who.int",
        "gender": "Genderqueer",
        "ip_address": "96.121.151.74"
    }, {
        "id": 52,
        "first_name": "Emlen",
        "last_name": "Motton",
        "email": "emotton1f@zdnet.com",
        "gender": "Bigender",
        "ip_address": "22.250.65.206"
    }, {
        "id": 53,
        "first_name": "Ethyl",
        "last_name": "Giraudat",
        "email": "egiraudat1g@jimdo.com",
        "gender": "Bigender",
        "ip_address": "34.223.218.220"
    }, {
        "id": 54,
        "first_name": "Sauncho",
        "last_name": "Costard",
        "email": "scostard1h@google.cn",
        "gender": "Genderfluid",
        "ip_address": "90.50.207.76"
    }, {
        "id": 55,
        "first_name": "Bowie",
        "last_name": "Feast",
        "email": "bfeast1i@cafepress.com",
        "gender": "Non-binary",
        "ip_address": "15.127.142.197"
    }, {
        "id": 56,
        "first_name": "Eadie",
        "last_name": "Robbel",
        "email": "erobbel1j@sun.com",
        "gender": "Genderfluid",
        "ip_address": "128.197.1.10"
    }, {
        "id": 57,
        "first_name": "Ransell",
        "last_name": "Bonhan",
        "email": "rbonhan1k@prweb.com",
        "gender": "Female",
        "ip_address": "70.88.173.47"
    }, {
        "id": 58,
        "first_name": "Anson",
        "last_name": "Jedrysik",
        "email": "ajedrysik1l@statcounter.com",
        "gender": "Female",
        "ip_address": "24.40.186.87"
    }, {
        "id": 59,
        "first_name": "Alaster",
        "last_name": "Lack",
        "email": "alack1m@gnu.org",
        "gender": "Genderfluid",
        "ip_address": "67.238.224.198"
    }, {
        "id": 60,
        "first_name": "Neville",
        "last_name": "Boggis",
        "email": "nboggis1n@arstechnica.com",
        "gender": "Bigender",
        "ip_address": "223.52.98.171"
    }, {
        "id": 61,
        "first_name": "Ethelin",
        "last_name": "Jarman",
        "email": "ejarman1o@people.com.cn",
        "gender": "Agender",
        "ip_address": "189.43.155.100"
    }, {
        "id": 62,
        "first_name": "Shep",
        "last_name": "Longmaid",
        "email": "slongmaid1p@multiply.com",
        "gender": "Female",
        "ip_address": "223.189.235.176"
    }, {
        "id": 63,
        "first_name": "Jane",
        "last_name": "Maiklem",
        "email": "jmaiklem1q@auda.org.au",
        "gender": "Genderfluid",
        "ip_address": "51.71.113.149"
    }, {
        "id": 64,
        "first_name": "Rowney",
        "last_name": "Najera",
        "email": "rnajera1r@pen.io",
        "gender": "Female",
        "ip_address": "20.79.105.161"
    }, {
        "id": 65,
        "first_name": "Vin",
        "last_name": "Conaboy",
        "email": "vconaboy1s@goodreads.com",
        "gender": "Female",
        "ip_address": "42.82.211.18"
    }, {
        "id": 66,
        "first_name": "Dewitt",
        "last_name": "Rennox",
        "email": "drennox1t@usnews.com",
        "gender": "Genderfluid",
        "ip_address": "99.94.22.29"
    }, {
        "id": 67,
        "first_name": "Rog",
        "last_name": "Flecknoe",
        "email": "rflecknoe1u@google.co.uk",
        "gender": "Bigender",
        "ip_address": "176.4.114.136"
    }, {
        "id": 68,
        "first_name": "Brandais",
        "last_name": "Sollitt",
        "email": "bsollitt1v@quantcast.com",
        "gender": "Agender",
        "ip_address": "189.233.9.110"
    }, {
        "id": 69,
        "first_name": "Sherman",
        "last_name": "Rivilis",
        "email": "srivilis1w@si.edu",
        "gender": "Agender",
        "ip_address": "123.216.151.90"
    }, {
        "id": 70,
        "first_name": "Abel",
        "last_name": "MacCrossan",
        "email": "amaccrossan1x@tmall.com",
        "gender": "Polygender",
        "ip_address": "108.105.76.7"
    }, {
        "id": 71,
        "first_name": "Jamison",
        "last_name": "Carnalan",
        "email": "jcarnalan1y@linkedin.com",
        "gender": "Genderqueer",
        "ip_address": "80.113.63.101"
    }, {
        "id": 72,
        "first_name": "Denys",
        "last_name": "Whiten",
        "email": "dwhiten1z@bigcartel.com",
        "gender": "Female",
        "ip_address": "255.254.108.195"
    }, {
        "id": 73,
        "first_name": "Callida",
        "last_name": "Gladhill",
        "email": "cgladhill20@bigcartel.com",
        "gender": "Male",
        "ip_address": "6.103.86.192"
    }, {
        "id": 74,
        "first_name": "Antonia",
        "last_name": "Habershon",
        "email": "ahabershon21@dailymail.co.uk",
        "gender": "Genderfluid",
        "ip_address": "4.207.15.125"
    }, {
        "id": 75,
        "first_name": "Tobie",
        "last_name": "Tesoe",
        "email": "ttesoe22@mac.com",
        "gender": "Female",
        "ip_address": "226.99.117.137"
    }, {
        "id": 76,
        "first_name": "Josselyn",
        "last_name": "O'Leagham",
        "email": "joleagham23@nbcnews.com",
        "gender": "Non-binary",
        "ip_address": "123.132.184.107"
    }, {
        "id": 77,
        "first_name": "Gael",
        "last_name": "Prahm",
        "email": "gprahm24@technorati.com",
        "gender": "Male",
        "ip_address": "117.186.243.240"
    }, {
        "id": 78,
        "first_name": "Josefina",
        "last_name": "Giraldon",
        "email": "jgiraldon25@sfgate.com",
        "gender": "Polygender",
        "ip_address": "137.133.47.75"
    }, {
        "id": 79,
        "first_name": "Emile",
        "last_name": "Tilbrook",
        "email": "etilbrook26@about.me",
        "gender": "Male",
        "ip_address": "29.94.237.244"
    }, {
        "id": 80,
        "first_name": "Armstrong",
        "last_name": "Scurfield",
        "email": "ascurfield27@wikimedia.org",
        "gender": "Agender",
        "ip_address": "51.139.93.93"
    }, {
        "id": 81,
        "first_name": "Kyrstin",
        "last_name": "Francom",
        "email": "kfrancom28@discovery.com",
        "gender": "Female",
        "ip_address": "6.229.158.69"
    }, {
        "id": 82,
        "first_name": "Torrance",
        "last_name": "Clowney",
        "email": "tclowney29@zdnet.com",
        "gender": "Polygender",
        "ip_address": "9.79.131.11"
    }, {
        "id": 83,
        "first_name": "Brewster",
        "last_name": "Rocks",
        "email": "brocks2a@domainmarket.com",
        "gender": "Agender",
        "ip_address": "195.254.210.194"
    }, {
        "id": 84,
        "first_name": "Cleopatra",
        "last_name": "Adicot",
        "email": "cadicot2b@sitemeter.com",
        "gender": "Agender",
        "ip_address": "165.118.205.174"
    }, {
        "id": 85,
        "first_name": "Elbert",
        "last_name": "Chalfant",
        "email": "echalfant2c@amazon.com",
        "gender": "Genderqueer",
        "ip_address": "59.136.228.105"
    }, {
        "id": 86,
        "first_name": "Trenna",
        "last_name": "Bossingham",
        "email": "tbossingham2d@storify.com",
        "gender": "Non-binary",
        "ip_address": "111.223.147.131"
    }, {
        "id": 87,
        "first_name": "Lidia",
        "last_name": "Guthrie",
        "email": "lguthrie2e@biblegateway.com",
        "gender": "Non-binary",
        "ip_address": "87.43.99.114"
    }, {
        "id": 88,
        "first_name": "Elset",
        "last_name": "Boissier",
        "email": "eboissier2f@oakley.com",
        "gender": "Agender",
        "ip_address": "217.116.67.74"
    }, {
        "id": 89,
        "first_name": "Rodina",
        "last_name": "Gelland",
        "email": "rgelland2g@macromedia.com",
        "gender": "Bigender",
        "ip_address": "90.69.62.253"
    }, {
        "id": 90,
        "first_name": "Johann",
        "last_name": "Mariel",
        "email": "jmariel2h@behance.net",
        "gender": "Genderfluid",
        "ip_address": "152.27.8.212"
    }, {
        "id": 91,
        "first_name": "Jody",
        "last_name": "Earpe",
        "email": "jearpe2i@rediff.com",
        "gender": "Female",
        "ip_address": "10.111.169.33"
    }, {
        "id": 92,
        "first_name": "Salomo",
        "last_name": "Veart",
        "email": "sveart2j@bizjournals.com",
        "gender": "Agender",
        "ip_address": "248.183.143.92"
    }, {
        "id": 93,
        "first_name": "Tailor",
        "last_name": "Moorman",
        "email": "tmoorman2k@ovh.net",
        "gender": "Agender",
        "ip_address": "102.176.87.152"
    }, {
        "id": 94,
        "first_name": "Dominga",
        "last_name": "Ianno",
        "email": "dianno2l@answers.com",
        "gender": "Non-binary",
        "ip_address": "60.162.166.208"
    }, {
        "id": 95,
        "first_name": "Joellyn",
        "last_name": "Gunther",
        "email": "jgunther2m@google.nl",
        "gender": "Male",
        "ip_address": "17.233.48.43"
    }, {
        "id": 96,
        "first_name": "Gabriell",
        "last_name": "Lingfoot",
        "email": "glingfoot2n@angelfire.com",
        "gender": "Male",
        "ip_address": "248.224.127.139"
    }, {
        "id": 97,
        "first_name": "Rosalynd",
        "last_name": "Birtles",
        "email": "rbirtles2o@yolasite.com",
        "gender": "Genderqueer",
        "ip_address": "147.77.113.208"
    }, {
        "id": 98,
        "first_name": "Cammy",
        "last_name": "Lethebridge",
        "email": "clethebridge2p@archive.org",
        "gender": "Genderqueer",
        "ip_address": "167.125.108.198"
    }, {
        "id": 99,
        "first_name": "Anatol",
        "last_name": "Learoid",
        "email": "alearoid2q@yelp.com",
        "gender": "Genderfluid",
        "ip_address": "194.129.175.208"
    }, {
        "id": 100,
        "first_name": "Orelie",
        "last_name": "Shirlaw",
        "email": "oshirlaw2r@time.com",
        "gender": "Agender",
        "ip_address": "90.146.162.150"
    }];
    return data;
}

function addForm() {
    
}

module.exports = {
    getList
}